---
- hosts: windows_servers
  gather_facts: no
  tasks:
    - name: Install Windows updates
      ansible.windows.win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
        reboot: yes
